name: Task
description: Task
title: "[Task]: "
labels: ["Task"]
projects: "github/1"
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Descripcion
      description: "Descripcion de la tarea"
      value: Descripcion de la tarea 
  - type: dropdown
    id: Prioridad
    attributes:
      label: Prioridad
      options:
        - label: Alta
        - label: Media
        - label: Baja
    validations:
      required: false
  - type: textarea
    id: criterios_aceptacion
    attributes:
      label: Criterios de Aceptacion
      description: "Como validar que la tarea es correcta"
      value: |
        1.
        2.
        3.
        ...
