name: User Story
description: User Story
title: "[User Story]: "
labels: ["User Story"]
body:
  - type: textarea
    id: UserStory
    attributes:
      label: User Story Descripcion
      description: "Descripcion"
      value: |
        ## Descripcion


        ```[tasklist]
        ### Tareas
        - [ ] Tarea 1
        - [ ] Tarea 2
        ``` 
  - type: dropdown
    id: Prioridad
    attributes:
      label: Prioridad
      options:
        - Alta
        - Media
        - Baja
    validations:
      required: false
  - type: textarea
    id: criterios_aceptacion
    attributes:
      label: Criterios de Aceptacion
      description: "Como validar que la tarea es correcta"
      value: |
        1.
        2.
        3.
        ...
