name: Move assigned pull requests into In Progress

on:
  issue:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Scrapper Infracciones
          column: In Progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}
