name: Tests my action
on:
  push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: Freihart512/move-linked-pr-issue@v0.0.6
        with: 
          project_name: Scrapper Infracciones
          user_name: Freihart512
          github_token: ${{ secrets.GITHUB_TOKEN }}
