name: Tests my action
on:
  push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: Freihart512/move-linked-pr-issue@v0.0.2
        with: 
          projectNAme: Scrapper Infracciones
          github_token: ${{ secrets.GITHUB_TOKEN }}
