name: Tests my action
on:
  issues:
    types: [assigned]
jobs:
  testing:
    runs-on: ubuntu-latest
    - uses: Freihart512/move-linked-pr-issue@v0.0.1
      with: 
        projectNAme: Scrapper Infracciones
        github_token: ${{ secrets.GITHUB_TOKEN }}


    