name: Tests my action
on:
  push
jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      repository-projects: write
      issues: write
    steps:
      - uses: Freihart512/move-linked-pr-issue@v0.0.20
        with: 
          project_name: Scrapper Infracciones
          user_name: Freihart512
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{secrets.GITHUB_TOKEN}}
