name: Tests
on:
  issues:
    types: [assigned]

jobs:
  getCardInfo:
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'latest release: ${{ github.event.node_id }}'"
        id: get_card_info
      - run: |
          gh api graphql -f query='
            query { 
                node(id: "${{ github.event.issue.node_id }}") {
                ... on Issue {
                 __typename
                id
                number
                title
                labels(first: 100) {
                  edges {
                    __typename
                    node {
                      name
                    }
                  }
                }
                projectItems(first: 1) {
                  nodes {
                    project {
                      title
                      id
                    }
                    id
                    __typename
                    fieldValueByName(name: "Status") {
                      __typename
                      ... on ProjectV2ItemFieldSingleSelectValue {
                        name
                        id
                      }
                    }
                  }
                }
              }
            }
          }' > project_data.json
          
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - run: "echo 'PROJECT_ID='$(jq '.data.node.title' project_data.json) >> $GITHUB_ENV"
      - run: "echo Output [$PROJECT_ID]" 
